# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-19 15:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FilmRevolutionApp', '0003_auto_20170419_1342'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seriereview',
            old_name='movie',
            new_name='serie',
        ),
    ]
